### PR TITLE
Added video timestamps to every talk

### PR DESCRIPTION
**Pull request by Noezor**
Thanks for the great workshop !

I added link to videos + timestamps of every talk and lightning of the workshop. It should work fine with just this change.

### CODE REVIEW

**Comment by bouthilx** [comment]
Thank you! We need to confirm with all presenters before making it available on the website.

**Comment by ryan-lowe** [comment]
@bouthilx I can send emails to the presenters. Should I make it opt-out (we are planning to post the slides to the website in 3 days, let us know if you do not want this), or opt-in (we want your confirmation to put the slides up). My first guess is opt-out (since the talks are already publicly available), but wanted to ask opinions. 
@jzf2101 @koustuvsinha @Breakend

**Comment by ryan-lowe** [comment]
also, thank you so much @Noezor!! :D

**Comment by shagunsodhani** [comment]
Opt out makes more sense.

Cheers,
Shagun
https://shagunsodhani.com

**Comment by koustuvsinha** [comment]
Video links are being re-directed to other videos of the workshop. Mailed Slideslive regarding this.

**Pull request merged**
